[2018-07-16 16:23:08 -0400] [9680] [CRITICAL] WORKER TIMEOUT (pid:9687)
[2018-07-16 16:27:10 -0400] [9843] [CRITICAL] WORKER TIMEOUT (pid:9850)
[2018-07-16 18:43:08 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:10283)
[2018-07-16 18:43:08 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:10284)
[2018-07-16 18:43:08 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:10285)
[2018-07-16 18:43:08 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:10286)
[2018-07-16 18:43:08 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:10287)
[2018-07-16 18:43:08 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:10288)
[2018-07-16 18:43:08 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:10289)
[2018-07-16 18:43:08 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:10290)
[2018-07-16 18:43:08 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:10291)
[2018-07-16 20:43:59 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:10358)
[2018-07-16 20:43:59 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:10350)
[2018-07-16 20:43:59 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:10351)
[2018-07-16 20:43:59 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:10352)
[2018-07-16 20:43:59 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:10354)
[2018-07-16 20:43:59 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:10355)
[2018-07-16 20:43:59 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:10356)
[2018-07-16 20:43:59 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:10357)
[2018-07-16 20:43:59 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:10349)
[2018-07-16 22:44:50 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:10374)
[2018-07-16 22:44:50 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:10375)
[2018-07-16 22:44:50 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:10376)
[2018-07-16 22:44:50 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:10377)
[2018-07-16 22:44:50 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:10378)
[2018-07-16 22:44:50 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:10379)
[2018-07-16 22:44:50 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:10380)
[2018-07-16 22:44:50 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:10381)
[2018-07-16 22:44:50 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:10382)
[2018-07-17 00:45:41 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:10400)
[2018-07-17 00:45:41 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:10401)
[2018-07-17 00:45:41 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:10402)
[2018-07-17 00:45:41 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:10403)
[2018-07-17 00:45:41 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:10404)
[2018-07-17 00:45:41 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:10405)
[2018-07-17 00:45:41 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:10396)
[2018-07-17 00:45:41 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:10398)
[2018-07-17 00:45:41 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:10399)
[2018-07-17 02:46:32 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:10432)
[2018-07-17 02:46:32 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:10433)
[2018-07-17 02:46:32 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:10434)
[2018-07-17 02:46:32 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:10425)
[2018-07-17 02:46:32 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:10426)
[2018-07-17 02:46:32 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:10428)
[2018-07-17 02:46:32 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:10429)
[2018-07-17 02:46:32 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:10430)
[2018-07-17 02:46:32 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:10431)
[2018-07-17 04:47:23 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:10451)
[2018-07-17 04:47:23 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:10452)
[2018-07-17 04:47:23 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:10453)
[2018-07-17 04:47:23 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:10454)
[2018-07-17 04:47:23 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:10455)
[2018-07-17 04:47:23 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:10456)
[2018-07-17 04:47:23 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:10457)
[2018-07-17 04:47:23 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:10458)
[2018-07-17 04:47:23 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:10459)
[2018-07-17 05:49:02 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:10481)
[2018-07-17 05:49:02 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:10483)
[2018-07-17 05:49:02 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:10485)
[2018-07-17 05:49:02 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:10486)
[2018-07-17 05:49:02 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:10487)
[2018-07-17 05:49:02 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:10488)
[2018-07-17 05:49:02 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:10474)
[2018-07-17 05:49:02 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:10475)
[2018-07-17 05:49:02 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:10476)
[2018-07-17 08:45:43 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:10688)
[2018-07-17 10:03:40 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:10690)
[2018-07-17 10:03:40 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:12739)
[2018-07-17 10:03:40 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:10689)
[2018-07-17 10:03:40 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:10682)
[2018-07-17 10:03:40 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:10683)
[2018-07-17 10:03:40 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:10684)
[2018-07-17 10:03:40 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:10685)
[2018-07-17 10:03:40 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:10686)
[2018-07-17 10:03:40 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:10687)
[2018-07-17 10:08:39 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:13718)
[2018-07-17 10:08:39 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:13719)
[2018-07-17 10:08:39 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:13720)
[2018-07-17 10:08:39 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:13721)
[2018-07-17 10:08:39 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:13722)
[2018-07-17 10:08:39 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:13723)
[2018-07-17 10:08:39 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:13724)
[2018-07-17 10:08:39 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:13725)
[2018-07-17 10:08:39 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:13726)
[2018-07-17 10:18:37 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:13764)
[2018-07-17 10:18:37 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:13765)
[2018-07-17 10:18:37 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:13766)
[2018-07-17 10:18:37 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:13767)
[2018-07-17 10:18:37 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:13768)
[2018-07-17 10:18:37 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:13769)
[2018-07-17 10:18:37 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:13770)
[2018-07-17 10:18:37 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:13771)
[2018-07-17 10:18:37 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:13772)
[2018-07-17 10:30:08 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:13872)
[2018-07-17 10:30:08 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:13873)
[2018-07-17 10:30:08 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:13874)
[2018-07-17 10:30:08 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:13875)
[2018-07-17 10:30:08 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:13876)
[2018-07-17 10:30:08 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:13878)
[2018-07-17 10:30:08 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:13879)
[2018-07-17 10:30:08 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:13870)
[2018-07-17 10:30:08 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:13871)
[2018-07-17 16:53:38 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:13893)
[2018-07-17 16:53:38 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:13894)
[2018-07-17 16:53:38 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:13896)
[2018-07-17 16:53:38 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:13897)
[2018-07-17 16:53:38 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:13898)
[2018-07-17 16:53:38 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:13899)
[2018-07-17 16:53:38 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:13900)
[2018-07-17 16:53:38 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:13901)
[2018-07-17 16:53:38 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:13902)
[2018-07-17 17:00:49 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:15239)
[2018-07-17 17:00:49 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:15240)
[2018-07-17 17:00:49 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:15241)
[2018-07-17 17:00:49 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:15242)
[2018-07-17 17:00:49 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:15243)
[2018-07-17 17:00:49 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:15244)
[2018-07-17 17:00:49 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:15245)
[2018-07-17 17:00:49 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:15246)
[2018-07-17 17:00:49 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:15247)
[2018-07-17 19:03:25 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:15261)
[2018-07-17 19:03:25 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:15262)
[2018-07-17 19:03:25 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:15263)
[2018-07-17 19:03:25 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:15264)
[2018-07-17 19:03:25 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:15265)
[2018-07-17 19:03:25 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:15266)
[2018-07-17 19:03:25 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:15267)
[2018-07-17 19:03:25 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:15268)
[2018-07-17 19:03:25 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:15269)
[2018-07-17 19:18:40 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:15303)
[2018-07-17 19:18:40 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:15304)
[2018-07-17 19:18:40 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:15306)
[2018-07-17 19:18:40 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:15307)
[2018-07-17 19:18:40 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:15308)
[2018-07-17 19:18:40 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:15309)
[2018-07-17 19:18:40 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:15310)
[2018-07-17 19:18:40 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:15311)
[2018-07-17 19:18:40 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:15312)
[2018-07-17 20:20:11 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:15331)
[2018-07-17 20:20:11 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:15332)
[2018-07-17 20:20:11 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:15334)
[2018-07-17 20:20:11 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:15335)
[2018-07-17 20:20:11 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:15337)
[2018-07-17 20:20:11 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:15338)
[2018-07-17 20:20:11 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:15339)
[2018-07-17 20:20:11 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:15340)
[2018-07-17 20:20:11 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:15341)
[2018-07-18 05:20:22 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:15834)
[2018-07-18 05:20:22 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:15835)
[2018-07-18 05:20:22 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:15836)
[2018-07-18 05:20:22 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:15837)
[2018-07-18 05:20:22 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:15838)
[2018-07-18 05:20:22 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:15839)
[2018-07-18 05:20:22 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:15840)
[2018-07-18 05:20:22 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:15841)
[2018-07-18 05:20:22 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:15842)
[2018-07-18 05:42:22 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:16274)
[2018-07-18 05:42:22 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:16275)
[2018-07-18 05:42:22 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:16276)
[2018-07-18 05:42:22 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:16277)
[2018-07-18 05:42:22 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:16278)
[2018-07-18 05:42:22 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:16279)
[2018-07-18 06:29:50 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:16271)
[2018-07-18 09:12:24 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:16272)
[2018-07-18 09:12:24 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:16349)
[2018-07-18 09:14:24 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:18608)
[2018-07-18 09:19:17 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:16356)
[2018-07-18 09:23:10 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:16347)
[2018-07-18 09:31:59 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:16351)
[2018-07-18 09:32:30 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:16346)
[2018-07-18 09:36:18 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:19228)
[2018-07-18 09:37:44 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:16273)
[2018-07-18 09:58:30 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:19220)
[2018-07-18 09:58:30 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:16348)
[2018-07-18 09:58:30 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:16350)
[2018-07-18 09:58:30 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:19359)
[2018-07-18 09:58:30 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:18914)
[2018-07-18 09:58:30 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:19305)
[2018-07-18 09:58:30 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:18730)
[2018-07-18 09:58:30 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:19053)
[2018-07-18 09:58:30 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:18609)
[2018-07-18 10:41:11 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:19393)
[2018-07-18 10:41:11 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:19394)
[2018-07-18 10:41:11 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:19395)
[2018-07-18 10:41:11 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:19396)
[2018-07-18 10:41:11 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:19397)
[2018-07-18 10:41:11 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:19398)
[2018-07-18 10:41:11 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:19399)
[2018-07-18 10:41:11 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:19400)
[2018-07-18 10:41:11 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:19401)
[2018-07-18 12:04:06 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:19797)
[2018-07-18 12:31:34 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:19816)
[2018-07-18 12:31:34 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:19799)
[2018-07-18 12:31:34 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:19800)
[2018-07-18 12:31:34 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:19801)
[2018-07-18 12:31:34 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:19802)
[2018-07-18 12:31:34 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:19803)
[2018-07-18 12:31:34 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:19804)
[2018-07-18 12:31:34 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:19805)
[2018-07-18 12:31:34 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:19806)
[2018-07-18 13:11:02 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:20129)
[2018-07-18 13:11:02 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:20130)
[2018-07-18 13:11:02 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:20131)
[2018-07-18 13:11:02 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:20132)
[2018-07-18 13:11:02 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:20133)
[2018-07-18 13:11:02 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:20134)
[2018-07-18 13:11:02 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:20135)
[2018-07-18 13:11:02 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:20136)
[2018-07-18 13:11:02 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:20138)
[2018-07-18 13:14:10 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:20528)
[2018-07-18 13:14:10 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:20529)
[2018-07-18 13:14:10 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:20530)
[2018-07-18 13:14:10 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:20531)
[2018-07-18 13:14:10 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:20532)
[2018-07-18 13:14:10 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:20524)
[2018-07-18 13:14:10 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:20525)
[2018-07-18 13:14:10 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:20526)
[2018-07-18 13:14:10 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:20527)
[2018-07-18 13:31:39 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:20562)
[2018-07-18 13:31:39 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:20563)
[2018-07-18 13:31:39 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:20564)
[2018-07-18 13:31:39 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:20565)
[2018-07-18 13:31:39 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:20566)
[2018-07-18 13:31:39 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:20567)
[2018-07-18 13:31:39 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:20568)
[2018-07-18 13:31:39 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:20569)
[2018-07-18 13:31:39 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:20570)
[2018-07-18 14:04:29 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:20697)
[2018-07-18 14:06:19 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:20701)
[2018-07-18 14:07:57 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:20696)
[2018-07-18 14:10:56 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:20698)
[2018-07-18 14:14:16 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:20700)
[2018-07-18 15:11:23 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:20694)
[2018-07-18 15:24:29 -0400] [10279] [CRITICAL] WORKER TIMEOUT (pid:21352)
[2018-07-18 15:45:51 -0400] [23272] [CRITICAL] WORKER TIMEOUT (pid:23282)
[2018-07-18 15:56:25 -0400] [23512] [CRITICAL] WORKER TIMEOUT (pid:23522)
[2018-07-18 15:57:27 -0400] [23512] [CRITICAL] WORKER TIMEOUT (pid:23519)
[2018-07-18 18:04:18 -0400] [23512] [CRITICAL] WORKER TIMEOUT (pid:23778)
[2018-07-18 18:04:18 -0400] [23512] [CRITICAL] WORKER TIMEOUT (pid:23779)
[2018-07-18 18:04:18 -0400] [23512] [CRITICAL] WORKER TIMEOUT (pid:23780)
[2018-07-18 18:04:18 -0400] [23512] [CRITICAL] WORKER TIMEOUT (pid:23781)
[2018-07-18 18:04:18 -0400] [23512] [CRITICAL] WORKER TIMEOUT (pid:23782)
[2018-07-18 18:04:18 -0400] [23512] [CRITICAL] WORKER TIMEOUT (pid:23784)
[2018-07-18 18:04:18 -0400] [23512] [CRITICAL] WORKER TIMEOUT (pid:23786)
[2018-07-18 18:04:18 -0400] [23512] [CRITICAL] WORKER TIMEOUT (pid:23787)
[2018-07-18 18:04:18 -0400] [23512] [CRITICAL] WORKER TIMEOUT (pid:23788)
[2018-07-18 19:04:18 -0400] [23512] [CRITICAL] WORKER TIMEOUT (pid:23808)
[2018-07-18 19:04:18 -0400] [23512] [CRITICAL] WORKER TIMEOUT (pid:23809)
[2018-07-18 19:04:18 -0400] [23512] [CRITICAL] WORKER TIMEOUT (pid:23810)
[2018-07-18 19:04:18 -0400] [23512] [CRITICAL] WORKER TIMEOUT (pid:23811)
[2018-07-18 19:04:18 -0400] [23512] [CRITICAL] WORKER TIMEOUT (pid:23812)
[2018-07-18 19:04:18 -0400] [23512] [CRITICAL] WORKER TIMEOUT (pid:23813)
[2018-07-18 19:04:18 -0400] [23512] [CRITICAL] WORKER TIMEOUT (pid:23814)
[2018-07-18 19:04:18 -0400] [23512] [CRITICAL] WORKER TIMEOUT (pid:23806)
[2018-07-18 19:04:18 -0400] [23512] [CRITICAL] WORKER TIMEOUT (pid:23807)
[2018-07-19 01:05:01 -0400] [23512] [CRITICAL] WORKER TIMEOUT (pid:23820)
[2018-07-19 01:05:01 -0400] [23512] [CRITICAL] WORKER TIMEOUT (pid:23821)
[2018-07-19 01:05:01 -0400] [23512] [CRITICAL] WORKER TIMEOUT (pid:23822)
[2018-07-19 01:05:01 -0400] [23512] [CRITICAL] WORKER TIMEOUT (pid:23823)
[2018-07-19 01:05:01 -0400] [23512] [CRITICAL] WORKER TIMEOUT (pid:23824)
[2018-07-19 01:05:01 -0400] [23512] [CRITICAL] WORKER TIMEOUT (pid:23825)
[2018-07-19 01:05:01 -0400] [23512] [CRITICAL] WORKER TIMEOUT (pid:23826)
[2018-07-19 01:05:01 -0400] [23512] [CRITICAL] WORKER TIMEOUT (pid:23827)
[2018-07-19 01:05:01 -0400] [23512] [CRITICAL] WORKER TIMEOUT (pid:23829)
[2018-07-19 03:05:15 -0400] [23512] [CRITICAL] WORKER TIMEOUT (pid:23863)
[2018-07-19 04:05:17 -0400] [23512] [CRITICAL] WORKER TIMEOUT (pid:23878)
[2018-07-19 08:15:26 -0400] [23512] [CRITICAL] WORKER TIMEOUT (pid:23889)
[2018-07-19 08:15:26 -0400] [23512] [CRITICAL] WORKER TIMEOUT (pid:23864)
[2018-07-19 08:15:26 -0400] [23512] [CRITICAL] WORKER TIMEOUT (pid:23865)
[2018-07-19 08:15:26 -0400] [23512] [CRITICAL] WORKER TIMEOUT (pid:23866)
[2018-07-19 08:15:26 -0400] [23512] [CRITICAL] WORKER TIMEOUT (pid:23867)
[2018-07-19 08:15:26 -0400] [23512] [CRITICAL] WORKER TIMEOUT (pid:23868)
[2018-07-19 08:15:26 -0400] [23512] [CRITICAL] WORKER TIMEOUT (pid:23869)
[2018-07-19 08:15:26 -0400] [23512] [CRITICAL] WORKER TIMEOUT (pid:23870)
[2018-07-19 08:15:26 -0400] [23512] [CRITICAL] WORKER TIMEOUT (pid:23871)
[2018-07-19 08:43:50,719] ERROR in app: Exception on /ad [GET]
Traceback (most recent call last):
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/user_utils.py", line 20, in new_func
    resp = make_response(func(*args, **kwargs))
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 280, in advertisement
    filter(Participant.workerid == worker_id).\
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2535, in count
    return self.from_self(col).scalar()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2341, in scalar
    ret = self.one()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2310, in one
    ret = list(self)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2353, in __iter__
    return self._execute_and_instances(context)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2366, in _execute_and_instances
    close_with_result=True)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2357, in _connection_from_session
    **kw)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 799, in connection
    close_with_result=close_with_result)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 803, in _connection_for_bind
    return self.transaction._connection_for_bind(engine)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 299, in _connection_for_bind
    conn = bind.contextual_connect()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1661, in contextual_connect
    self.pool.connect(),
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/pool.py", line 272, in connect
    return _ConnectionFairy(self).checkout()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/pool.py", line 431, in __init__
    rec = self._connection_record = pool._do_get()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/pool.py", line 867, in _do_get
    return self._create_connection()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/pool.py", line 225, in _create_connection
    return _ConnectionRecord(self)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/pool.py", line 318, in __init__
    self.connection = self.__connect()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/pool.py", line 379, in __connect
    connection = self.__pool._creator()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 80, in connect
    return dialect.connect(*cargs, **cparams)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 283, in connect
    return self.dbapi.connect(*cargs, **cparams)
OperationalError: (OperationalError) unable to open database file None None
[2018-07-19 08:45:03 -0400] [24529] [CRITICAL] WORKER TIMEOUT (pid:24540)
[2018-07-19 08:48:40 -0400] [24529] [CRITICAL] WORKER TIMEOUT (pid:24541)
[2018-07-19 09:02:42 -0400] [24529] [CRITICAL] WORKER TIMEOUT (pid:24538)
[2018-07-19 09:03:45 -0400] [24529] [CRITICAL] WORKER TIMEOUT (pid:24533)
[2018-07-19 09:13:13 -0400] [24529] [CRITICAL] WORKER TIMEOUT (pid:24837)
[2018-07-19 09:24:24 -0400] [24529] [CRITICAL] WORKER TIMEOUT (pid:24536)
[2018-07-19 09:30:03 -0400] [24529] [CRITICAL] WORKER TIMEOUT (pid:24570)
[2018-07-19 09:30:44 -0400] [24529] [CRITICAL] WORKER TIMEOUT (pid:24535)
[2018-07-19 09:31:51 -0400] [24529] [CRITICAL] WORKER TIMEOUT (pid:25270)
[2018-07-19 09:48:21 -0400] [24529] [CRITICAL] WORKER TIMEOUT (pid:24964)
[2018-07-19 09:48:54 -0400] [24529] [CRITICAL] WORKER TIMEOUT (pid:24539)
[2018-07-19 14:43:58 -0400] [28377] [CRITICAL] WORKER TIMEOUT (pid:28645)
[2018-07-19 14:43:58 -0400] [28377] [CRITICAL] WORKER TIMEOUT (pid:28647)
[2018-07-19 14:43:58 -0400] [28377] [CRITICAL] WORKER TIMEOUT (pid:28649)
[2018-07-19 14:43:58 -0400] [28377] [CRITICAL] WORKER TIMEOUT (pid:28650)
[2018-07-19 14:43:58 -0400] [28377] [CRITICAL] WORKER TIMEOUT (pid:28651)
[2018-07-19 14:43:58 -0400] [28377] [CRITICAL] WORKER TIMEOUT (pid:28652)
[2018-07-19 14:43:58 -0400] [28377] [CRITICAL] WORKER TIMEOUT (pid:28653)
[2018-07-19 14:43:58 -0400] [28377] [CRITICAL] WORKER TIMEOUT (pid:28659)
[2018-07-19 14:43:58 -0400] [28377] [CRITICAL] WORKER TIMEOUT (pid:28663)
[2018-07-19 15:40:21 -0400] [29708] [CRITICAL] WORKER TIMEOUT (pid:29712)
[2018-07-19 15:40:21 -0400] [29708] [CRITICAL] WORKER TIMEOUT (pid:29713)
[2018-07-19 15:40:21 -0400] [29708] [CRITICAL] WORKER TIMEOUT (pid:29714)
[2018-07-19 15:40:21 -0400] [29708] [CRITICAL] WORKER TIMEOUT (pid:29715)
[2018-07-19 15:40:21 -0400] [29708] [CRITICAL] WORKER TIMEOUT (pid:29716)
[2018-07-19 15:40:21 -0400] [29708] [CRITICAL] WORKER TIMEOUT (pid:29717)
[2018-07-19 15:40:21 -0400] [29708] [CRITICAL] WORKER TIMEOUT (pid:29718)
[2018-07-19 15:40:21 -0400] [29708] [CRITICAL] WORKER TIMEOUT (pid:29719)
[2018-07-19 15:40:21 -0400] [29708] [CRITICAL] WORKER TIMEOUT (pid:29720)
[2018-07-19 17:27:48 -0400] [30671] [CRITICAL] WORKER TIMEOUT (pid:31008)
[2018-07-19 17:27:48 -0400] [30671] [CRITICAL] WORKER TIMEOUT (pid:31009)
[2018-07-19 17:27:48 -0400] [30671] [CRITICAL] WORKER TIMEOUT (pid:31010)
[2018-07-19 17:27:48 -0400] [30671] [CRITICAL] WORKER TIMEOUT (pid:31012)
[2018-07-19 17:27:48 -0400] [30671] [CRITICAL] WORKER TIMEOUT (pid:31013)
[2018-07-19 17:27:48 -0400] [30671] [CRITICAL] WORKER TIMEOUT (pid:31015)
[2018-07-19 17:27:48 -0400] [30671] [CRITICAL] WORKER TIMEOUT (pid:31016)
[2018-07-19 17:27:48 -0400] [30671] [CRITICAL] WORKER TIMEOUT (pid:31018)
[2018-07-19 17:27:48 -0400] [30671] [CRITICAL] WORKER TIMEOUT (pid:31007)
[2018-07-19 17:34:28 -0400] [30671] [CRITICAL] WORKER TIMEOUT (pid:31664)
[2018-07-19 17:34:28 -0400] [30671] [CRITICAL] WORKER TIMEOUT (pid:31665)
[2018-07-19 17:34:28 -0400] [30671] [CRITICAL] WORKER TIMEOUT (pid:31666)
[2018-07-19 17:34:28 -0400] [30671] [CRITICAL] WORKER TIMEOUT (pid:31667)
[2018-07-19 17:34:28 -0400] [30671] [CRITICAL] WORKER TIMEOUT (pid:31668)
[2018-07-19 17:34:28 -0400] [30671] [CRITICAL] WORKER TIMEOUT (pid:31669)
[2018-07-19 17:34:28 -0400] [30671] [CRITICAL] WORKER TIMEOUT (pid:31670)
[2018-07-19 17:34:28 -0400] [30671] [CRITICAL] WORKER TIMEOUT (pid:31671)
[2018-07-19 17:34:28 -0400] [30671] [CRITICAL] WORKER TIMEOUT (pid:31672)
[2018-07-19 17:49:43 -0400] [30671] [CRITICAL] WORKER TIMEOUT (pid:31753)
[2018-07-19 17:49:43 -0400] [30671] [CRITICAL] WORKER TIMEOUT (pid:31754)
[2018-07-19 17:49:43 -0400] [30671] [CRITICAL] WORKER TIMEOUT (pid:31755)
[2018-07-19 17:49:43 -0400] [30671] [CRITICAL] WORKER TIMEOUT (pid:31756)
[2018-07-19 17:49:43 -0400] [30671] [CRITICAL] WORKER TIMEOUT (pid:31757)
[2018-07-19 17:49:43 -0400] [30671] [CRITICAL] WORKER TIMEOUT (pid:31758)
[2018-07-19 17:49:43 -0400] [30671] [CRITICAL] WORKER TIMEOUT (pid:31759)
[2018-07-19 17:49:43 -0400] [30671] [CRITICAL] WORKER TIMEOUT (pid:31760)
[2018-07-19 17:49:43 -0400] [30671] [CRITICAL] WORKER TIMEOUT (pid:31761)
[2018-07-19 18:08:08 -0400] [30671] [CRITICAL] WORKER TIMEOUT (pid:31792)
[2018-07-19 18:08:08 -0400] [30671] [CRITICAL] WORKER TIMEOUT (pid:31793)
[2018-07-19 18:08:08 -0400] [30671] [CRITICAL] WORKER TIMEOUT (pid:31794)
[2018-07-19 18:08:08 -0400] [30671] [CRITICAL] WORKER TIMEOUT (pid:31795)
[2018-07-19 18:08:08 -0400] [30671] [CRITICAL] WORKER TIMEOUT (pid:31796)
[2018-07-19 18:08:08 -0400] [30671] [CRITICAL] WORKER TIMEOUT (pid:31797)
[2018-07-19 18:08:08 -0400] [30671] [CRITICAL] WORKER TIMEOUT (pid:31798)
[2018-07-19 18:08:08 -0400] [30671] [CRITICAL] WORKER TIMEOUT (pid:31799)
[2018-07-19 18:08:08 -0400] [30671] [CRITICAL] WORKER TIMEOUT (pid:31800)
[2018-07-19 18:58:06 -0400] [30671] [CRITICAL] WORKER TIMEOUT (pid:31834)
[2018-07-19 18:58:06 -0400] [30671] [CRITICAL] WORKER TIMEOUT (pid:31835)
[2018-07-19 18:58:06 -0400] [30671] [CRITICAL] WORKER TIMEOUT (pid:31836)
[2018-07-19 18:58:06 -0400] [30671] [CRITICAL] WORKER TIMEOUT (pid:31837)
[2018-07-19 18:58:06 -0400] [30671] [CRITICAL] WORKER TIMEOUT (pid:31838)
[2018-07-19 18:58:06 -0400] [30671] [CRITICAL] WORKER TIMEOUT (pid:31839)
[2018-07-19 18:58:06 -0400] [30671] [CRITICAL] WORKER TIMEOUT (pid:31840)
[2018-07-19 18:58:06 -0400] [30671] [CRITICAL] WORKER TIMEOUT (pid:31841)
[2018-07-19 18:58:06 -0400] [30671] [CRITICAL] WORKER TIMEOUT (pid:31842)
[2018-07-19 20:59:41 -0400] [30671] [CRITICAL] WORKER TIMEOUT (pid:31874)
[2018-07-19 20:59:41 -0400] [30671] [CRITICAL] WORKER TIMEOUT (pid:31875)
[2018-07-19 20:59:41 -0400] [30671] [CRITICAL] WORKER TIMEOUT (pid:31876)
[2018-07-19 20:59:41 -0400] [30671] [CRITICAL] WORKER TIMEOUT (pid:31878)
[2018-07-19 20:59:41 -0400] [30671] [CRITICAL] WORKER TIMEOUT (pid:31879)
[2018-07-19 20:59:41 -0400] [30671] [CRITICAL] WORKER TIMEOUT (pid:31880)
[2018-07-19 23:00:33 -0400] [30671] [CRITICAL] WORKER TIMEOUT (pid:31881)
[2018-07-19 23:00:33 -0400] [30671] [CRITICAL] WORKER TIMEOUT (pid:31882)
[2018-07-19 23:00:33 -0400] [30671] [CRITICAL] WORKER TIMEOUT (pid:31883)
[2018-07-20 01:01:25 -0400] [30671] [CRITICAL] WORKER TIMEOUT (pid:32014)
[2018-07-20 01:01:25 -0400] [30671] [CRITICAL] WORKER TIMEOUT (pid:32015)
[2018-07-20 01:01:25 -0400] [30671] [CRITICAL] WORKER TIMEOUT (pid:32016)
[2018-07-20 01:01:25 -0400] [30671] [CRITICAL] WORKER TIMEOUT (pid:32017)
[2018-07-20 01:01:25 -0400] [30671] [CRITICAL] WORKER TIMEOUT (pid:32020)
[2018-07-20 01:01:25 -0400] [30671] [CRITICAL] WORKER TIMEOUT (pid:32021)
[2018-07-20 01:01:25 -0400] [30671] [CRITICAL] WORKER TIMEOUT (pid:32034)
[2018-07-20 01:01:25 -0400] [30671] [CRITICAL] WORKER TIMEOUT (pid:32036)
[2018-07-20 01:01:25 -0400] [30671] [CRITICAL] WORKER TIMEOUT (pid:32037)
[2018-07-20 03:02:17 -0400] [30671] [CRITICAL] WORKER TIMEOUT (pid:32052)
[2018-07-20 05:03:09 -0400] [30671] [CRITICAL] WORKER TIMEOUT (pid:32078)
[2018-07-20 05:03:09 -0400] [30671] [CRITICAL] WORKER TIMEOUT (pid:32054)
[2018-07-20 05:03:09 -0400] [30671] [CRITICAL] WORKER TIMEOUT (pid:32055)
[2018-07-20 05:03:09 -0400] [30671] [CRITICAL] WORKER TIMEOUT (pid:32056)
[2018-07-20 05:03:09 -0400] [30671] [CRITICAL] WORKER TIMEOUT (pid:32057)
[2018-07-20 05:03:09 -0400] [30671] [CRITICAL] WORKER TIMEOUT (pid:32058)
[2018-07-20 05:03:09 -0400] [30671] [CRITICAL] WORKER TIMEOUT (pid:32059)
[2018-07-20 05:03:09 -0400] [30671] [CRITICAL] WORKER TIMEOUT (pid:32060)
[2018-07-20 05:03:09 -0400] [30671] [CRITICAL] WORKER TIMEOUT (pid:32061)
[2018-07-20 05:26:54 -0400] [30671] [CRITICAL] WORKER TIMEOUT (pid:32097)
[2018-07-20 05:26:54 -0400] [30671] [CRITICAL] WORKER TIMEOUT (pid:32107)
[2018-07-20 05:26:54 -0400] [30671] [CRITICAL] WORKER TIMEOUT (pid:32111)
[2018-07-24 10:42:43 -0400] [53194] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 47, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 89, in <module>
    init_db()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/db.py", line 37, in init_db
    Base.metadata.create_all(bind=engine)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/schema.py", line 2848, in create_all
    tables=tables)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1479, in _run_visitor
    conn._run_visitor(visitorcallable, element, **kwargs)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1122, in _run_visitor
    **kwargs).traverse_single(element)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/sql/visitors.py", line 122, in traverse_single
    return meth(obj, **kw)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/ddl.py", line 70, in visit_metadata
    self.traverse_single(table, create_ok=True)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/sql/visitors.py", line 122, in traverse_single
    return meth(obj, **kw)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/ddl.py", line 89, in visit_table
    self.connection.execute(schema.CreateTable(table))
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 662, in execute
    params)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 720, in _execute_ddl
    compiled
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 874, in _execute_context
    context)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1024, in _handle_dbapi_exception
    exc_info
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 196, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 867, in _execute_context
    context)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 324, in do_execute
    cursor.execute(statement, parameters)
OperationalError: (OperationalError) table pilot already exists u'\nCREATE TABLE pilot (\n\tuniqueid VARCHAR(128) NOT NULL, \n\tassignmentid VARCHAR(128) NOT NULL, \n\tworkerid VARCHAR(128) NOT NULL, \n\thitid VARCHAR(128) NOT NULL, \n\tipaddress VARCHAR(128), \n\tbrowser VARCHAR(128), \n\tplatform VARCHAR(128), \n\tlanguage VARCHAR(128), \n\tcond INTEGER, \n\tcounterbalance INTEGER, \n\tcodeversion VARCHAR(128), \n\tbeginhit DATETIME, \n\tbeginexp DATETIME, \n\tendhit DATETIME, \n\tbonus FLOAT, \n\tstatus INTEGER, \n\tmode VARCHAR(128), \n\tdatastring TEXT(4294967295), \n\tPRIMARY KEY (uniqueid)\n)\n\n' ()
Traceback (most recent call last):
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 47, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 89, in <module>
    init_db()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/db.py", line 37, in init_db
    Base.metadata.create_all(bind=engine)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/schema.py", line 2848, in create_all
    tables=tables)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1479, in _run_visitor
    conn._run_visitor(visitorcallable, element, **kwargs)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1122, in _run_visitor
    **kwargs).traverse_single(element)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/sql/visitors.py", line 122, in traverse_single
    return meth(obj, **kw)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/ddl.py", line 70, in visit_metadata
    self.traverse_single(table, create_ok=True)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/sql/visitors.py", line 122, in traverse_single
    return meth(obj, **kw)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/ddl.py", line 89, in visit_table
    self.connection.execute(schema.CreateTable(table))
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 662, in execute
    params)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 720, in _execute_ddl
    compiled
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 874, in _execute_context
    context)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1024, in _handle_dbapi_exception
    exc_info
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 196, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 867, in _execute_context
    context)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 324, in do_execute
    cursor.execute(statement, parameters)
OperationalError: (OperationalError) table pilot already exists u'\nCREATE TABLE pilot (\n\tuniqueid VARCHAR(128) NOT NULL, \n\tassignmentid VARCHAR(128) NOT NULL, \n\tworkerid VARCHAR(128) NOT NULL, \n\thitid VARCHAR(128) NOT NULL, \n\tipaddress VARCHAR(128), \n\tbrowser VARCHAR(128), \n\tplatform VARCHAR(128), \n\tlanguage VARCHAR(128), \n\tcond INTEGER, \n\tcounterbalance INTEGER, \n\tcodeversion VARCHAR(128), \n\tbeginhit DATETIME, \n\tbeginexp DATETIME, \n\tendhit DATETIME, \n\tbonus FLOAT, \n\tstatus INTEGER, \n\tmode VARCHAR(128), \n\tdatastring TEXT(4294967295), \n\tPRIMARY KEY (uniqueid)\n)\n\n' ()
[2018-07-24 11:44:34,628] ERROR in app: Exception on /compute_bonus [GET]
Traceback (most recent call last):
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 724, in regularpage
    return render_template(pagename)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/flask/templating.py", line 133, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/flask/templating.py", line 57, in get_source
    return self._get_source_fast(environment, template)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/flask/templating.py", line 85, in _get_source_fast
    raise TemplateNotFound(template)
TemplateNotFound: compute_bonus
[2018-07-24 11:49:13,101] ERROR in app: Exception on /compute_bonus [GET]
Traceback (most recent call last):
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 724, in regularpage
    return render_template(pagename)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/flask/templating.py", line 133, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/flask/templating.py", line 57, in get_source
    return self._get_source_fast(environment, template)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/flask/templating.py", line 85, in _get_source_fast
    raise TemplateNotFound(template)
TemplateNotFound: compute_bonus
[2018-07-24 12:11:01 -0400] [55303] [CRITICAL] WORKER TIMEOUT (pid:55307)
[2018-07-24 12:11:01 -0400] [55303] [CRITICAL] WORKER TIMEOUT (pid:55308)
[2018-07-24 12:11:01 -0400] [55303] [CRITICAL] WORKER TIMEOUT (pid:55309)
[2018-07-24 12:11:01 -0400] [55303] [CRITICAL] WORKER TIMEOUT (pid:55310)
[2018-07-24 12:11:01 -0400] [55303] [CRITICAL] WORKER TIMEOUT (pid:55311)
[2018-07-24 12:11:01 -0400] [55303] [CRITICAL] WORKER TIMEOUT (pid:55312)
[2018-07-24 12:11:01 -0400] [55303] [CRITICAL] WORKER TIMEOUT (pid:55313)
[2018-07-24 12:11:01 -0400] [55303] [CRITICAL] WORKER TIMEOUT (pid:55314)
[2018-07-24 12:11:01 -0400] [55303] [CRITICAL] WORKER TIMEOUT (pid:55315)
[2018-07-24 12:55:52 -0400] [55303] [CRITICAL] WORKER TIMEOUT (pid:55520)
[2018-07-24 12:55:52 -0400] [55303] [CRITICAL] WORKER TIMEOUT (pid:55521)
[2018-07-24 12:55:52 -0400] [55303] [CRITICAL] WORKER TIMEOUT (pid:55522)
[2018-07-24 12:55:52 -0400] [55303] [CRITICAL] WORKER TIMEOUT (pid:55523)
[2018-07-24 12:55:52 -0400] [55303] [CRITICAL] WORKER TIMEOUT (pid:55515)
[2018-07-24 12:55:52 -0400] [55303] [CRITICAL] WORKER TIMEOUT (pid:55516)
[2018-07-24 12:55:52 -0400] [55303] [CRITICAL] WORKER TIMEOUT (pid:55517)
[2018-07-24 12:55:52 -0400] [55303] [CRITICAL] WORKER TIMEOUT (pid:55518)
[2018-07-24 12:55:52 -0400] [55303] [CRITICAL] WORKER TIMEOUT (pid:55519)
[2018-07-24 14:46:38 -0400] [57199] [CRITICAL] WORKER TIMEOUT (pid:57203)
[2018-07-24 14:46:38 -0400] [57199] [CRITICAL] WORKER TIMEOUT (pid:57204)
[2018-07-24 14:46:38 -0400] [57199] [CRITICAL] WORKER TIMEOUT (pid:57205)
[2018-07-24 14:46:38 -0400] [57199] [CRITICAL] WORKER TIMEOUT (pid:57206)
[2018-07-24 14:46:38 -0400] [57199] [CRITICAL] WORKER TIMEOUT (pid:57207)
[2018-07-24 14:46:38 -0400] [57199] [CRITICAL] WORKER TIMEOUT (pid:57208)
[2018-07-24 14:46:38 -0400] [57199] [CRITICAL] WORKER TIMEOUT (pid:57209)
[2018-07-24 14:46:38 -0400] [57199] [CRITICAL] WORKER TIMEOUT (pid:57210)
[2018-07-24 14:46:38 -0400] [57199] [CRITICAL] WORKER TIMEOUT (pid:57211)
[2018-07-24 14:53:44 -0400] [57199] [CRITICAL] WORKER TIMEOUT (pid:57365)
[2018-07-24 14:53:44 -0400] [57199] [CRITICAL] WORKER TIMEOUT (pid:57366)
[2018-07-24 14:53:44 -0400] [57199] [CRITICAL] WORKER TIMEOUT (pid:57367)
[2018-07-24 14:53:44 -0400] [57199] [CRITICAL] WORKER TIMEOUT (pid:57368)
[2018-07-24 14:53:44 -0400] [57199] [CRITICAL] WORKER TIMEOUT (pid:57369)
[2018-07-24 14:53:44 -0400] [57199] [CRITICAL] WORKER TIMEOUT (pid:57370)
[2018-07-24 14:53:44 -0400] [57199] [CRITICAL] WORKER TIMEOUT (pid:57371)
[2018-07-24 14:53:44 -0400] [57199] [CRITICAL] WORKER TIMEOUT (pid:57372)
[2018-07-24 14:53:44 -0400] [57199] [CRITICAL] WORKER TIMEOUT (pid:57373)
[2018-07-24 14:55:40 -0400] [57199] [CRITICAL] WORKER TIMEOUT (pid:57389)
[2018-07-24 14:55:40 -0400] [57199] [CRITICAL] WORKER TIMEOUT (pid:57390)
[2018-07-24 14:55:40 -0400] [57199] [CRITICAL] WORKER TIMEOUT (pid:57391)
[2018-07-24 14:55:40 -0400] [57199] [CRITICAL] WORKER TIMEOUT (pid:57392)
[2018-07-24 14:55:40 -0400] [57199] [CRITICAL] WORKER TIMEOUT (pid:57393)
[2018-07-24 14:55:40 -0400] [57199] [CRITICAL] WORKER TIMEOUT (pid:57394)
[2018-07-24 14:55:40 -0400] [57199] [CRITICAL] WORKER TIMEOUT (pid:57395)
[2018-07-24 14:55:40 -0400] [57199] [CRITICAL] WORKER TIMEOUT (pid:57396)
[2018-07-24 14:55:40 -0400] [57199] [CRITICAL] WORKER TIMEOUT (pid:57397)
[2018-07-24 14:58:27 -0400] [57199] [CRITICAL] WORKER TIMEOUT (pid:57408)
[2018-07-24 14:58:27 -0400] [57199] [CRITICAL] WORKER TIMEOUT (pid:57409)
[2018-07-24 14:58:27 -0400] [57199] [CRITICAL] WORKER TIMEOUT (pid:57410)
[2018-07-24 14:58:27 -0400] [57199] [CRITICAL] WORKER TIMEOUT (pid:57411)
[2018-07-24 14:58:27 -0400] [57199] [CRITICAL] WORKER TIMEOUT (pid:57412)
[2018-07-24 14:58:27 -0400] [57199] [CRITICAL] WORKER TIMEOUT (pid:57413)
[2018-07-24 14:58:27 -0400] [57199] [CRITICAL] WORKER TIMEOUT (pid:57414)
[2018-07-24 14:58:27 -0400] [57199] [CRITICAL] WORKER TIMEOUT (pid:57415)
[2018-07-24 14:58:27 -0400] [57199] [CRITICAL] WORKER TIMEOUT (pid:57416)
[2018-07-24 15:19:05 -0400] [57199] [CRITICAL] WORKER TIMEOUT (pid:57429)
[2018-07-24 15:19:05 -0400] [57199] [CRITICAL] WORKER TIMEOUT (pid:57430)
[2018-07-24 15:19:05 -0400] [57199] [CRITICAL] WORKER TIMEOUT (pid:57431)
[2018-07-24 15:19:05 -0400] [57199] [CRITICAL] WORKER TIMEOUT (pid:57432)
[2018-07-24 15:19:05 -0400] [57199] [CRITICAL] WORKER TIMEOUT (pid:57433)
[2018-07-24 15:19:05 -0400] [57199] [CRITICAL] WORKER TIMEOUT (pid:57434)
[2018-07-24 15:19:05 -0400] [57199] [CRITICAL] WORKER TIMEOUT (pid:57435)
[2018-07-24 15:19:05 -0400] [57199] [CRITICAL] WORKER TIMEOUT (pid:57436)
[2018-07-24 15:19:05 -0400] [57199] [CRITICAL] WORKER TIMEOUT (pid:57437)
[2018-07-24 16:16:47 -0400] [57199] [CRITICAL] WORKER TIMEOUT (pid:57450)
[2018-07-24 16:16:47 -0400] [57199] [CRITICAL] WORKER TIMEOUT (pid:57451)
[2018-07-24 16:16:47 -0400] [57199] [CRITICAL] WORKER TIMEOUT (pid:57452)
[2018-07-24 16:16:47 -0400] [57199] [CRITICAL] WORKER TIMEOUT (pid:57453)
[2018-07-24 16:16:47 -0400] [57199] [CRITICAL] WORKER TIMEOUT (pid:57454)
[2018-07-24 16:16:47 -0400] [57199] [CRITICAL] WORKER TIMEOUT (pid:57455)
[2018-07-24 16:16:47 -0400] [57199] [CRITICAL] WORKER TIMEOUT (pid:57456)
[2018-07-24 16:16:47 -0400] [57199] [CRITICAL] WORKER TIMEOUT (pid:57457)
[2018-07-24 16:16:47 -0400] [57199] [CRITICAL] WORKER TIMEOUT (pid:57458)
[2018-07-24 16:25:28 -0400] [57199] [CRITICAL] WORKER TIMEOUT (pid:57472)
[2018-07-24 16:25:28 -0400] [57199] [CRITICAL] WORKER TIMEOUT (pid:57474)
[2018-07-24 16:25:28 -0400] [57199] [CRITICAL] WORKER TIMEOUT (pid:57475)
[2018-07-24 16:25:28 -0400] [57199] [CRITICAL] WORKER TIMEOUT (pid:57476)
[2018-07-24 16:25:28 -0400] [57199] [CRITICAL] WORKER TIMEOUT (pid:57477)
[2018-07-24 16:25:28 -0400] [57199] [CRITICAL] WORKER TIMEOUT (pid:57478)
[2018-07-24 16:25:28 -0400] [57199] [CRITICAL] WORKER TIMEOUT (pid:57479)
[2018-07-24 16:25:28 -0400] [57199] [CRITICAL] WORKER TIMEOUT (pid:57470)
[2018-07-24 16:25:28 -0400] [57199] [CRITICAL] WORKER TIMEOUT (pid:57471)
[2018-07-24 16:26:41 -0400] [57199] [CRITICAL] WORKER TIMEOUT (pid:57494)
[2018-07-24 16:26:41 -0400] [57199] [CRITICAL] WORKER TIMEOUT (pid:57495)
[2018-07-24 16:26:41 -0400] [57199] [CRITICAL] WORKER TIMEOUT (pid:57496)
[2018-07-24 16:26:41 -0400] [57199] [CRITICAL] WORKER TIMEOUT (pid:57497)
[2018-07-24 16:26:41 -0400] [57199] [CRITICAL] WORKER TIMEOUT (pid:57498)
[2018-07-24 16:26:41 -0400] [57199] [CRITICAL] WORKER TIMEOUT (pid:57499)
[2018-07-24 16:26:41 -0400] [57199] [CRITICAL] WORKER TIMEOUT (pid:57500)
[2018-07-24 16:26:41 -0400] [57199] [CRITICAL] WORKER TIMEOUT (pid:57501)
[2018-07-24 16:26:41 -0400] [57199] [CRITICAL] WORKER TIMEOUT (pid:57502)
[2018-07-24 16:27:54 -0400] [57199] [CRITICAL] WORKER TIMEOUT (pid:57518)
[2018-07-24 16:27:54 -0400] [57199] [CRITICAL] WORKER TIMEOUT (pid:57519)
[2018-07-24 16:27:54 -0400] [57199] [CRITICAL] WORKER TIMEOUT (pid:57520)
[2018-07-24 16:27:54 -0400] [57199] [CRITICAL] WORKER TIMEOUT (pid:57521)
[2018-07-24 16:27:54 -0400] [57199] [CRITICAL] WORKER TIMEOUT (pid:57522)
[2018-07-24 16:27:54 -0400] [57199] [CRITICAL] WORKER TIMEOUT (pid:57524)
[2018-07-24 16:27:54 -0400] [57199] [CRITICAL] WORKER TIMEOUT (pid:57525)
[2018-07-24 16:27:54 -0400] [57199] [CRITICAL] WORKER TIMEOUT (pid:57532)
[2018-07-24 16:27:54 -0400] [57199] [CRITICAL] WORKER TIMEOUT (pid:57533)
[2018-07-24 17:35:09 -0400] [57199] [CRITICAL] WORKER TIMEOUT (pid:57556)
[2018-07-24 17:35:09 -0400] [57199] [CRITICAL] WORKER TIMEOUT (pid:57557)
[2018-07-24 17:35:09 -0400] [57199] [CRITICAL] WORKER TIMEOUT (pid:57558)
[2018-07-24 17:35:09 -0400] [57199] [CRITICAL] WORKER TIMEOUT (pid:57559)
[2018-07-24 17:35:09 -0400] [57199] [CRITICAL] WORKER TIMEOUT (pid:57560)
[2018-07-24 17:35:09 -0400] [57199] [CRITICAL] WORKER TIMEOUT (pid:57561)
[2018-07-24 17:35:09 -0400] [57199] [CRITICAL] WORKER TIMEOUT (pid:57562)
[2018-07-24 17:35:09 -0400] [57199] [CRITICAL] WORKER TIMEOUT (pid:57564)
[2018-07-24 17:35:09 -0400] [57199] [CRITICAL] WORKER TIMEOUT (pid:57565)
[2018-07-25 09:32:09 -0400] [62301] [CRITICAL] WORKER TIMEOUT (pid:62305)
[2018-07-25 09:32:09 -0400] [62301] [CRITICAL] WORKER TIMEOUT (pid:62308)
[2018-07-25 09:32:09 -0400] [62301] [CRITICAL] WORKER TIMEOUT (pid:62309)
[2018-07-25 09:32:09 -0400] [62301] [CRITICAL] WORKER TIMEOUT (pid:62310)
[2018-07-25 09:32:09 -0400] [62301] [CRITICAL] WORKER TIMEOUT (pid:62312)
[2018-07-25 11:44:58 -0400] [64640] [CRITICAL] WORKER TIMEOUT (pid:64776)
[2018-07-25 11:44:58 -0400] [64640] [CRITICAL] WORKER TIMEOUT (pid:64777)
[2018-07-25 11:44:58 -0400] [64640] [CRITICAL] WORKER TIMEOUT (pid:64780)
[2018-07-25 11:44:58 -0400] [64640] [CRITICAL] WORKER TIMEOUT (pid:64783)
[2018-07-25 11:44:58 -0400] [64640] [CRITICAL] WORKER TIMEOUT (pid:64786)
[2018-07-25 11:44:58 -0400] [64640] [CRITICAL] WORKER TIMEOUT (pid:64788)
[2018-07-25 11:44:58 -0400] [64640] [CRITICAL] WORKER TIMEOUT (pid:64790)
[2018-07-25 11:44:58 -0400] [64640] [CRITICAL] WORKER TIMEOUT (pid:64791)
[2018-07-25 11:44:58 -0400] [64640] [CRITICAL] WORKER TIMEOUT (pid:64792)
[2018-07-25 12:34:43,993] ERROR in app: Exception on /exp [GET]
Traceback (most recent call last):
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/user_utils.py", line 20, in new_func
    resp = make_response(func(*args, **kwargs))
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 439, in start_exp
    db_session.commit()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/orm/scoping.py", line 149, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 721, in commit
    self.transaction.commit()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 354, in commit
    self._prepare_impl()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 334, in _prepare_impl
    self.session.flush()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1818, in flush
    self._flush(objects)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1936, in _flush
    transaction.rollback(_capture_exception=True)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 58, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1900, in _flush
    flush_context.execute()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 372, in execute
    rec.execute(self)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 525, in execute
    uow
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 64, in save_obj
    table, insert)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 541, in _emit_insert_statements
    execute(statement, multiparams)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 662, in execute
    params)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 761, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 874, in _execute_context
    context)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1024, in _handle_dbapi_exception
    exc_info
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 196, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 867, in _execute_context
    context)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 324, in do_execute
    cursor.execute(statement, parameters)
OperationalError: (OperationalError) database is locked u'INSERT INTO debug (uniqueid, assignmentid, workerid, hitid, ipaddress, browser, platform, language, cond, counterbalance, codeversion, beginhit, beginexp, endhit, bonus, status, mode, datastring) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' ('debug3EVMNU:debug1GUTOE', u'debug1GUTOE', u'debug3EVMNU', u'debug3B7DL2', '127.0.0.1', 'chrome', 'macos', 'UNKNOWN', 0, 0, '0.1', '2018-07-25 12:34:38.952372', None, None, 0.0, 1, u'debug', None)
[2018-07-25 12:34:45,079] ERROR in app: Exception on /exp [GET]
Traceback (most recent call last):
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/user_utils.py", line 20, in new_func
    resp = make_response(func(*args, **kwargs))
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 439, in start_exp
    db_session.commit()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/orm/scoping.py", line 149, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 721, in commit
    self.transaction.commit()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 354, in commit
    self._prepare_impl()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 334, in _prepare_impl
    self.session.flush()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1818, in flush
    self._flush(objects)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1936, in _flush
    transaction.rollback(_capture_exception=True)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 58, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1900, in _flush
    flush_context.execute()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 372, in execute
    rec.execute(self)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 525, in execute
    uow
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 64, in save_obj
    table, insert)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 541, in _emit_insert_statements
    execute(statement, multiparams)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 662, in execute
    params)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 761, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 874, in _execute_context
    context)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1024, in _handle_dbapi_exception
    exc_info
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 196, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 867, in _execute_context
    context)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 324, in do_execute
    cursor.execute(statement, parameters)
OperationalError: (OperationalError) database is locked u'INSERT INTO debug (uniqueid, assignmentid, workerid, hitid, ipaddress, browser, platform, language, cond, counterbalance, codeversion, beginhit, beginexp, endhit, bonus, status, mode, datastring) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' ('debug3EVMNU:debug1GUTOE', u'debug1GUTOE', u'debug3EVMNU', u'debug3B7DL2', '127.0.0.1', 'chrome', 'macos', 'UNKNOWN', 0, 0, '0.1', '2018-07-25 12:34:40.027213', None, None, 0.0, 1, u'debug', None)
[2018-07-25 12:35:04,277] ERROR in app: Exception on /exp [GET]
Traceback (most recent call last):
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/user_utils.py", line 20, in new_func
    resp = make_response(func(*args, **kwargs))
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 439, in start_exp
    db_session.commit()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/orm/scoping.py", line 149, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 721, in commit
    self.transaction.commit()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 354, in commit
    self._prepare_impl()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 334, in _prepare_impl
    self.session.flush()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1818, in flush
    self._flush(objects)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1936, in _flush
    transaction.rollback(_capture_exception=True)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 58, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1900, in _flush
    flush_context.execute()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 372, in execute
    rec.execute(self)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 525, in execute
    uow
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 64, in save_obj
    table, insert)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 541, in _emit_insert_statements
    execute(statement, multiparams)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 662, in execute
    params)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 761, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 874, in _execute_context
    context)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1024, in _handle_dbapi_exception
    exc_info
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 196, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 867, in _execute_context
    context)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 324, in do_execute
    cursor.execute(statement, parameters)
OperationalError: (OperationalError) database is locked u'INSERT INTO debug (uniqueid, assignmentid, workerid, hitid, ipaddress, browser, platform, language, cond, counterbalance, codeversion, beginhit, beginexp, endhit, bonus, status, mode, datastring) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' ('debug4XH6KW:debug3ZRCN1', u'debug3ZRCN1', u'debug4XH6KW', u'debug1BH7ID', '127.0.0.1', 'chrome', 'macos', 'UNKNOWN', 0, 0, '0.1', '2018-07-25 12:34:59.230245', None, None, 0.0, 1, u'debug', None)
[2018-07-25 12:40:21 -0400] [66403] [CRITICAL] WORKER TIMEOUT (pid:66407)
[2018-07-25 12:40:21 -0400] [66403] [CRITICAL] WORKER TIMEOUT (pid:66409)
[2018-07-25 12:40:21 -0400] [66403] [CRITICAL] WORKER TIMEOUT (pid:66414)
[2018-08-01 06:57:38 -0400] [78891] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 47, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 89, in <module>
    init_db()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/db.py", line 37, in init_db
    Base.metadata.create_all(bind=engine)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/schema.py", line 2848, in create_all
    tables=tables)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1479, in _run_visitor
    conn._run_visitor(visitorcallable, element, **kwargs)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1122, in _run_visitor
    **kwargs).traverse_single(element)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/sql/visitors.py", line 122, in traverse_single
    return meth(obj, **kw)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/ddl.py", line 70, in visit_metadata
    self.traverse_single(table, create_ok=True)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/sql/visitors.py", line 122, in traverse_single
    return meth(obj, **kw)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/ddl.py", line 89, in visit_table
    self.connection.execute(schema.CreateTable(table))
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 662, in execute
    params)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 720, in _execute_ddl
    compiled
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 874, in _execute_context
    context)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1024, in _handle_dbapi_exception
    exc_info
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 196, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 867, in _execute_context
    context)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 324, in do_execute
    cursor.execute(statement, parameters)
OperationalError: (OperationalError) table newcsw_pilot already exists u'\nCREATE TABLE newcsw_pilot (\n\tuniqueid VARCHAR(128) NOT NULL, \n\tassignmentid VARCHAR(128) NOT NULL, \n\tworkerid VARCHAR(128) NOT NULL, \n\thitid VARCHAR(128) NOT NULL, \n\tipaddress VARCHAR(128), \n\tbrowser VARCHAR(128), \n\tplatform VARCHAR(128), \n\tlanguage VARCHAR(128), \n\tcond INTEGER, \n\tcounterbalance INTEGER, \n\tcodeversion VARCHAR(128), \n\tbeginhit DATETIME, \n\tbeginexp DATETIME, \n\tendhit DATETIME, \n\tbonus FLOAT, \n\tstatus INTEGER, \n\tmode VARCHAR(128), \n\tdatastring TEXT(4294967295), \n\tPRIMARY KEY (uniqueid)\n)\n\n' ()
Traceback (most recent call last):
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 47, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 89, in <module>
    init_db()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/db.py", line 37, in init_db
    Base.metadata.create_all(bind=engine)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/schema.py", line 2848, in create_all
    tables=tables)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1479, in _run_visitor
    conn._run_visitor(visitorcallable, element, **kwargs)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1122, in _run_visitor
    **kwargs).traverse_single(element)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/sql/visitors.py", line 122, in traverse_single
    return meth(obj, **kw)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/ddl.py", line 70, in visit_metadata
    self.traverse_single(table, create_ok=True)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/sql/visitors.py", line 122, in traverse_single
    return meth(obj, **kw)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/ddl.py", line 89, in visit_table
    self.connection.execute(schema.CreateTable(table))
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 662, in execute
    params)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 720, in _execute_ddl
    compiled
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 874, in _execute_context
    context)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1024, in _handle_dbapi_exception
    exc_info
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 196, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 867, in _execute_context
    context)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 324, in do_execute
    cursor.execute(statement, parameters)
OperationalError: (OperationalError) table newcsw_pilot already exists u'\nCREATE TABLE newcsw_pilot (\n\tuniqueid VARCHAR(128) NOT NULL, \n\tassignmentid VARCHAR(128) NOT NULL, \n\tworkerid VARCHAR(128) NOT NULL, \n\thitid VARCHAR(128) NOT NULL, \n\tipaddress VARCHAR(128), \n\tbrowser VARCHAR(128), \n\tplatform VARCHAR(128), \n\tlanguage VARCHAR(128), \n\tcond INTEGER, \n\tcounterbalance INTEGER, \n\tcodeversion VARCHAR(128), \n\tbeginhit DATETIME, \n\tbeginexp DATETIME, \n\tendhit DATETIME, \n\tbonus FLOAT, \n\tstatus INTEGER, \n\tmode VARCHAR(128), \n\tdatastring TEXT(4294967295), \n\tPRIMARY KEY (uniqueid)\n)\n\n' ()
[2018-08-01 06:57:38 -0400] [78887] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 47, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 89, in <module>
    init_db()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/db.py", line 37, in init_db
    Base.metadata.create_all(bind=engine)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/schema.py", line 2848, in create_all
    tables=tables)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1479, in _run_visitor
    conn._run_visitor(visitorcallable, element, **kwargs)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1122, in _run_visitor
    **kwargs).traverse_single(element)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/sql/visitors.py", line 122, in traverse_single
    return meth(obj, **kw)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/ddl.py", line 70, in visit_metadata
    self.traverse_single(table, create_ok=True)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/sql/visitors.py", line 122, in traverse_single
    return meth(obj, **kw)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/ddl.py", line 89, in visit_table
    self.connection.execute(schema.CreateTable(table))
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 662, in execute
    params)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 720, in _execute_ddl
    compiled
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 874, in _execute_context
    context)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1024, in _handle_dbapi_exception
    exc_info
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 196, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 867, in _execute_context
    context)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 324, in do_execute
    cursor.execute(statement, parameters)
OperationalError: (OperationalError) table newcsw_pilot already exists u'\nCREATE TABLE newcsw_pilot (\n\tuniqueid VARCHAR(128) NOT NULL, \n\tassignmentid VARCHAR(128) NOT NULL, \n\tworkerid VARCHAR(128) NOT NULL, \n\thitid VARCHAR(128) NOT NULL, \n\tipaddress VARCHAR(128), \n\tbrowser VARCHAR(128), \n\tplatform VARCHAR(128), \n\tlanguage VARCHAR(128), \n\tcond INTEGER, \n\tcounterbalance INTEGER, \n\tcodeversion VARCHAR(128), \n\tbeginhit DATETIME, \n\tbeginexp DATETIME, \n\tendhit DATETIME, \n\tbonus FLOAT, \n\tstatus INTEGER, \n\tmode VARCHAR(128), \n\tdatastring TEXT(4294967295), \n\tPRIMARY KEY (uniqueid)\n)\n\n' ()
Traceback (most recent call last):
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 47, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 89, in <module>
    init_db()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/db.py", line 37, in init_db
    Base.metadata.create_all(bind=engine)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/schema.py", line 2848, in create_all
    tables=tables)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1479, in _run_visitor
    conn._run_visitor(visitorcallable, element, **kwargs)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1122, in _run_visitor
    **kwargs).traverse_single(element)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/sql/visitors.py", line 122, in traverse_single
    return meth(obj, **kw)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/ddl.py", line 70, in visit_metadata
    self.traverse_single(table, create_ok=True)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/sql/visitors.py", line 122, in traverse_single
    return meth(obj, **kw)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/ddl.py", line 89, in visit_table
    self.connection.execute(schema.CreateTable(table))
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 662, in execute
    params)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 720, in _execute_ddl
    compiled
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 874, in _execute_context
    context)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1024, in _handle_dbapi_exception
    exc_info
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 196, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 867, in _execute_context
    context)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 324, in do_execute
    cursor.execute(statement, parameters)
OperationalError: (OperationalError) table newcsw_pilot already exists u'\nCREATE TABLE newcsw_pilot (\n\tuniqueid VARCHAR(128) NOT NULL, \n\tassignmentid VARCHAR(128) NOT NULL, \n\tworkerid VARCHAR(128) NOT NULL, \n\thitid VARCHAR(128) NOT NULL, \n\tipaddress VARCHAR(128), \n\tbrowser VARCHAR(128), \n\tplatform VARCHAR(128), \n\tlanguage VARCHAR(128), \n\tcond INTEGER, \n\tcounterbalance INTEGER, \n\tcodeversion VARCHAR(128), \n\tbeginhit DATETIME, \n\tbeginexp DATETIME, \n\tendhit DATETIME, \n\tbonus FLOAT, \n\tstatus INTEGER, \n\tmode VARCHAR(128), \n\tdatastring TEXT(4294967295), \n\tPRIMARY KEY (uniqueid)\n)\n\n' ()
[2018-08-01 06:57:38 -0400] [78888] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 47, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 89, in <module>
    init_db()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/db.py", line 37, in init_db
    Base.metadata.create_all(bind=engine)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/schema.py", line 2848, in create_all
    tables=tables)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1479, in _run_visitor
    conn._run_visitor(visitorcallable, element, **kwargs)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1122, in _run_visitor
    **kwargs).traverse_single(element)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/sql/visitors.py", line 122, in traverse_single
    return meth(obj, **kw)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/ddl.py", line 70, in visit_metadata
    self.traverse_single(table, create_ok=True)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/sql/visitors.py", line 122, in traverse_single
    return meth(obj, **kw)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/ddl.py", line 89, in visit_table
    self.connection.execute(schema.CreateTable(table))
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 662, in execute
    params)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 720, in _execute_ddl
    compiled
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 874, in _execute_context
    context)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1024, in _handle_dbapi_exception
    exc_info
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 196, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 867, in _execute_context
    context)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 324, in do_execute
    cursor.execute(statement, parameters)
OperationalError: (OperationalError) table newcsw_pilot already exists u'\nCREATE TABLE newcsw_pilot (\n\tuniqueid VARCHAR(128) NOT NULL, \n\tassignmentid VARCHAR(128) NOT NULL, \n\tworkerid VARCHAR(128) NOT NULL, \n\thitid VARCHAR(128) NOT NULL, \n\tipaddress VARCHAR(128), \n\tbrowser VARCHAR(128), \n\tplatform VARCHAR(128), \n\tlanguage VARCHAR(128), \n\tcond INTEGER, \n\tcounterbalance INTEGER, \n\tcodeversion VARCHAR(128), \n\tbeginhit DATETIME, \n\tbeginexp DATETIME, \n\tendhit DATETIME, \n\tbonus FLOAT, \n\tstatus INTEGER, \n\tmode VARCHAR(128), \n\tdatastring TEXT(4294967295), \n\tPRIMARY KEY (uniqueid)\n)\n\n' ()
Traceback (most recent call last):
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 47, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 89, in <module>
    init_db()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/db.py", line 37, in init_db
    Base.metadata.create_all(bind=engine)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/schema.py", line 2848, in create_all
    tables=tables)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1479, in _run_visitor
    conn._run_visitor(visitorcallable, element, **kwargs)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1122, in _run_visitor
    **kwargs).traverse_single(element)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/sql/visitors.py", line 122, in traverse_single
    return meth(obj, **kw)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/ddl.py", line 70, in visit_metadata
    self.traverse_single(table, create_ok=True)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/sql/visitors.py", line 122, in traverse_single
    return meth(obj, **kw)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/ddl.py", line 89, in visit_table
    self.connection.execute(schema.CreateTable(table))
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 662, in execute
    params)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 720, in _execute_ddl
    compiled
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 874, in _execute_context
    context)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1024, in _handle_dbapi_exception
    exc_info
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 196, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 867, in _execute_context
    context)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 324, in do_execute
    cursor.execute(statement, parameters)
OperationalError: (OperationalError) table newcsw_pilot already exists u'\nCREATE TABLE newcsw_pilot (\n\tuniqueid VARCHAR(128) NOT NULL, \n\tassignmentid VARCHAR(128) NOT NULL, \n\tworkerid VARCHAR(128) NOT NULL, \n\thitid VARCHAR(128) NOT NULL, \n\tipaddress VARCHAR(128), \n\tbrowser VARCHAR(128), \n\tplatform VARCHAR(128), \n\tlanguage VARCHAR(128), \n\tcond INTEGER, \n\tcounterbalance INTEGER, \n\tcodeversion VARCHAR(128), \n\tbeginhit DATETIME, \n\tbeginexp DATETIME, \n\tendhit DATETIME, \n\tbonus FLOAT, \n\tstatus INTEGER, \n\tmode VARCHAR(128), \n\tdatastring TEXT(4294967295), \n\tPRIMARY KEY (uniqueid)\n)\n\n' ()
[2018-08-01 06:57:38 -0400] [78892] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 47, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 89, in <module>
    init_db()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/db.py", line 37, in init_db
    Base.metadata.create_all(bind=engine)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/schema.py", line 2848, in create_all
    tables=tables)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1479, in _run_visitor
    conn._run_visitor(visitorcallable, element, **kwargs)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1122, in _run_visitor
    **kwargs).traverse_single(element)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/sql/visitors.py", line 122, in traverse_single
    return meth(obj, **kw)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/ddl.py", line 70, in visit_metadata
    self.traverse_single(table, create_ok=True)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/sql/visitors.py", line 122, in traverse_single
    return meth(obj, **kw)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/ddl.py", line 89, in visit_table
    self.connection.execute(schema.CreateTable(table))
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 662, in execute
    params)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 720, in _execute_ddl
    compiled
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 874, in _execute_context
    context)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1024, in _handle_dbapi_exception
    exc_info
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 196, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 867, in _execute_context
    context)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 324, in do_execute
    cursor.execute(statement, parameters)
OperationalError: (OperationalError) table newcsw_pilot already exists u'\nCREATE TABLE newcsw_pilot (\n\tuniqueid VARCHAR(128) NOT NULL, \n\tassignmentid VARCHAR(128) NOT NULL, \n\tworkerid VARCHAR(128) NOT NULL, \n\thitid VARCHAR(128) NOT NULL, \n\tipaddress VARCHAR(128), \n\tbrowser VARCHAR(128), \n\tplatform VARCHAR(128), \n\tlanguage VARCHAR(128), \n\tcond INTEGER, \n\tcounterbalance INTEGER, \n\tcodeversion VARCHAR(128), \n\tbeginhit DATETIME, \n\tbeginexp DATETIME, \n\tendhit DATETIME, \n\tbonus FLOAT, \n\tstatus INTEGER, \n\tmode VARCHAR(128), \n\tdatastring TEXT(4294967295), \n\tPRIMARY KEY (uniqueid)\n)\n\n' ()
Traceback (most recent call last):
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 47, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 89, in <module>
    init_db()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/db.py", line 37, in init_db
    Base.metadata.create_all(bind=engine)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/schema.py", line 2848, in create_all
    tables=tables)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1479, in _run_visitor
    conn._run_visitor(visitorcallable, element, **kwargs)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1122, in _run_visitor
    **kwargs).traverse_single(element)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/sql/visitors.py", line 122, in traverse_single
    return meth(obj, **kw)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/ddl.py", line 70, in visit_metadata
    self.traverse_single(table, create_ok=True)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/sql/visitors.py", line 122, in traverse_single
    return meth(obj, **kw)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/ddl.py", line 89, in visit_table
    self.connection.execute(schema.CreateTable(table))
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 662, in execute
    params)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 720, in _execute_ddl
    compiled
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 874, in _execute_context
    context)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1024, in _handle_dbapi_exception
    exc_info
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 196, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 867, in _execute_context
    context)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 324, in do_execute
    cursor.execute(statement, parameters)
OperationalError: (OperationalError) table newcsw_pilot already exists u'\nCREATE TABLE newcsw_pilot (\n\tuniqueid VARCHAR(128) NOT NULL, \n\tassignmentid VARCHAR(128) NOT NULL, \n\tworkerid VARCHAR(128) NOT NULL, \n\thitid VARCHAR(128) NOT NULL, \n\tipaddress VARCHAR(128), \n\tbrowser VARCHAR(128), \n\tplatform VARCHAR(128), \n\tlanguage VARCHAR(128), \n\tcond INTEGER, \n\tcounterbalance INTEGER, \n\tcodeversion VARCHAR(128), \n\tbeginhit DATETIME, \n\tbeginexp DATETIME, \n\tendhit DATETIME, \n\tbonus FLOAT, \n\tstatus INTEGER, \n\tmode VARCHAR(128), \n\tdatastring TEXT(4294967295), \n\tPRIMARY KEY (uniqueid)\n)\n\n' ()
[2018-08-01 06:57:38 -0400] [78889] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 47, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 89, in <module>
    init_db()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/db.py", line 37, in init_db
    Base.metadata.create_all(bind=engine)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/schema.py", line 2848, in create_all
    tables=tables)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1479, in _run_visitor
    conn._run_visitor(visitorcallable, element, **kwargs)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1122, in _run_visitor
    **kwargs).traverse_single(element)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/sql/visitors.py", line 122, in traverse_single
    return meth(obj, **kw)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/ddl.py", line 70, in visit_metadata
    self.traverse_single(table, create_ok=True)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/sql/visitors.py", line 122, in traverse_single
    return meth(obj, **kw)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/ddl.py", line 89, in visit_table
    self.connection.execute(schema.CreateTable(table))
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 662, in execute
    params)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 720, in _execute_ddl
    compiled
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 874, in _execute_context
    context)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1024, in _handle_dbapi_exception
    exc_info
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 196, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 867, in _execute_context
    context)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 324, in do_execute
    cursor.execute(statement, parameters)
OperationalError: (OperationalError) table newcsw_pilot already exists u'\nCREATE TABLE newcsw_pilot (\n\tuniqueid VARCHAR(128) NOT NULL, \n\tassignmentid VARCHAR(128) NOT NULL, \n\tworkerid VARCHAR(128) NOT NULL, \n\thitid VARCHAR(128) NOT NULL, \n\tipaddress VARCHAR(128), \n\tbrowser VARCHAR(128), \n\tplatform VARCHAR(128), \n\tlanguage VARCHAR(128), \n\tcond INTEGER, \n\tcounterbalance INTEGER, \n\tcodeversion VARCHAR(128), \n\tbeginhit DATETIME, \n\tbeginexp DATETIME, \n\tendhit DATETIME, \n\tbonus FLOAT, \n\tstatus INTEGER, \n\tmode VARCHAR(128), \n\tdatastring TEXT(4294967295), \n\tPRIMARY KEY (uniqueid)\n)\n\n' ()
Traceback (most recent call last):
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 47, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 89, in <module>
    init_db()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/db.py", line 37, in init_db
    Base.metadata.create_all(bind=engine)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/schema.py", line 2848, in create_all
    tables=tables)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1479, in _run_visitor
    conn._run_visitor(visitorcallable, element, **kwargs)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1122, in _run_visitor
    **kwargs).traverse_single(element)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/sql/visitors.py", line 122, in traverse_single
    return meth(obj, **kw)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/ddl.py", line 70, in visit_metadata
    self.traverse_single(table, create_ok=True)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/sql/visitors.py", line 122, in traverse_single
    return meth(obj, **kw)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/ddl.py", line 89, in visit_table
    self.connection.execute(schema.CreateTable(table))
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 662, in execute
    params)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 720, in _execute_ddl
    compiled
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 874, in _execute_context
    context)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1024, in _handle_dbapi_exception
    exc_info
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 196, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 867, in _execute_context
    context)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 324, in do_execute
    cursor.execute(statement, parameters)
OperationalError: (OperationalError) table newcsw_pilot already exists u'\nCREATE TABLE newcsw_pilot (\n\tuniqueid VARCHAR(128) NOT NULL, \n\tassignmentid VARCHAR(128) NOT NULL, \n\tworkerid VARCHAR(128) NOT NULL, \n\thitid VARCHAR(128) NOT NULL, \n\tipaddress VARCHAR(128), \n\tbrowser VARCHAR(128), \n\tplatform VARCHAR(128), \n\tlanguage VARCHAR(128), \n\tcond INTEGER, \n\tcounterbalance INTEGER, \n\tcodeversion VARCHAR(128), \n\tbeginhit DATETIME, \n\tbeginexp DATETIME, \n\tendhit DATETIME, \n\tbonus FLOAT, \n\tstatus INTEGER, \n\tmode VARCHAR(128), \n\tdatastring TEXT(4294967295), \n\tPRIMARY KEY (uniqueid)\n)\n\n' ()
[2018-08-01 11:19:28 -0400] [80134] [CRITICAL] WORKER TIMEOUT (pid:80138)
[2018-08-01 11:19:28 -0400] [80134] [CRITICAL] WORKER TIMEOUT (pid:80139)
[2018-08-01 11:19:28 -0400] [80134] [CRITICAL] WORKER TIMEOUT (pid:80140)
[2018-08-01 11:19:28 -0400] [80134] [CRITICAL] WORKER TIMEOUT (pid:80141)
[2018-08-01 11:19:28 -0400] [80134] [CRITICAL] WORKER TIMEOUT (pid:80142)
[2018-08-01 11:19:28 -0400] [80134] [CRITICAL] WORKER TIMEOUT (pid:80143)
[2018-08-01 11:19:28 -0400] [80134] [CRITICAL] WORKER TIMEOUT (pid:80144)
[2018-08-01 11:19:28 -0400] [80134] [CRITICAL] WORKER TIMEOUT (pid:80145)
[2018-08-01 11:19:28 -0400] [80134] [CRITICAL] WORKER TIMEOUT (pid:80146)
[2018-08-01 12:39:29 -0400] [80134] [CRITICAL] WORKER TIMEOUT (pid:82785)
[2018-08-01 12:39:29 -0400] [80134] [CRITICAL] WORKER TIMEOUT (pid:82777)
[2018-08-01 12:39:29 -0400] [80134] [CRITICAL] WORKER TIMEOUT (pid:82779)
[2018-08-01 18:14:34 -0400] [80134] [CRITICAL] WORKER TIMEOUT (pid:84192)
[2018-08-01 18:14:34 -0400] [80134] [CRITICAL] WORKER TIMEOUT (pid:84193)
[2018-08-01 18:14:34 -0400] [80134] [CRITICAL] WORKER TIMEOUT (pid:82791)
[2018-08-01 18:14:34 -0400] [80134] [CRITICAL] WORKER TIMEOUT (pid:82775)
[2018-08-01 18:14:34 -0400] [80134] [CRITICAL] WORKER TIMEOUT (pid:82778)
[2018-08-01 18:14:34 -0400] [80134] [CRITICAL] WORKER TIMEOUT (pid:84191)
[2018-08-01 18:14:34 -0400] [80134] [CRITICAL] WORKER TIMEOUT (pid:82780)
[2018-08-01 18:14:34 -0400] [80134] [CRITICAL] WORKER TIMEOUT (pid:82781)
[2018-08-01 18:14:34 -0400] [80134] [CRITICAL] WORKER TIMEOUT (pid:82783)
[2018-08-01 19:14:45 -0400] [80134] [CRITICAL] WORKER TIMEOUT (pid:86792)
[2018-08-01 19:14:45 -0400] [80134] [CRITICAL] WORKER TIMEOUT (pid:86793)
[2018-08-01 19:14:45 -0400] [80134] [CRITICAL] WORKER TIMEOUT (pid:86794)
[2018-08-01 19:14:45 -0400] [80134] [CRITICAL] WORKER TIMEOUT (pid:86795)
[2018-08-01 19:14:45 -0400] [80134] [CRITICAL] WORKER TIMEOUT (pid:86796)
[2018-08-01 19:14:45 -0400] [80134] [CRITICAL] WORKER TIMEOUT (pid:86797)
[2018-08-01 19:14:45 -0400] [80134] [CRITICAL] WORKER TIMEOUT (pid:86798)
[2018-08-01 19:14:45 -0400] [80134] [CRITICAL] WORKER TIMEOUT (pid:86799)
[2018-08-01 19:14:45 -0400] [80134] [CRITICAL] WORKER TIMEOUT (pid:86800)
[2018-08-02 04:15:33 -0400] [80134] [CRITICAL] WORKER TIMEOUT (pid:86849)
[2018-08-02 05:36:46 -0400] [80134] [CRITICAL] WORKER TIMEOUT (pid:86850)
[2018-08-02 05:36:46 -0400] [80134] [CRITICAL] WORKER TIMEOUT (pid:86851)
[2018-08-02 05:36:46 -0400] [80134] [CRITICAL] WORKER TIMEOUT (pid:86852)
[2018-08-02 05:36:46 -0400] [80134] [CRITICAL] WORKER TIMEOUT (pid:86853)
[2018-08-02 05:36:46 -0400] [80134] [CRITICAL] WORKER TIMEOUT (pid:86854)
[2018-08-02 05:36:46 -0400] [80134] [CRITICAL] WORKER TIMEOUT (pid:86855)
[2018-08-02 05:36:46 -0400] [80134] [CRITICAL] WORKER TIMEOUT (pid:86856)
[2018-08-02 05:36:46 -0400] [80134] [CRITICAL] WORKER TIMEOUT (pid:86857)
[2018-08-02 12:00:40 -0400] [88201] [CRITICAL] WORKER TIMEOUT (pid:88832)
[2018-08-02 12:00:40 -0400] [88201] [CRITICAL] WORKER TIMEOUT (pid:88841)
[2018-08-02 12:00:40 -0400] [88201] [CRITICAL] WORKER TIMEOUT (pid:88823)
[2018-08-02 12:00:40 -0400] [88201] [CRITICAL] WORKER TIMEOUT (pid:88825)
[2018-08-02 12:00:40 -0400] [88201] [CRITICAL] WORKER TIMEOUT (pid:88827)
[2018-08-02 12:00:40 -0400] [88201] [CRITICAL] WORKER TIMEOUT (pid:88828)
[2018-08-02 12:00:40 -0400] [88201] [CRITICAL] WORKER TIMEOUT (pid:88829)
[2018-08-02 12:00:40 -0400] [88201] [CRITICAL] WORKER TIMEOUT (pid:88830)
[2018-08-02 12:00:40 -0400] [88201] [CRITICAL] WORKER TIMEOUT (pid:88831)
[2018-08-02 14:45:43 -0400] [95143] [CRITICAL] WORKER TIMEOUT (pid:95147)
[2018-08-02 14:45:44 -0400] [95143] [CRITICAL] WORKER TIMEOUT (pid:95148)
[2018-08-02 14:45:44 -0400] [95143] [CRITICAL] WORKER TIMEOUT (pid:95149)
[2018-08-02 14:45:44 -0400] [95143] [CRITICAL] WORKER TIMEOUT (pid:95150)
[2018-08-02 14:45:44 -0400] [95143] [CRITICAL] WORKER TIMEOUT (pid:95151)
[2018-08-02 14:45:44 -0400] [95143] [CRITICAL] WORKER TIMEOUT (pid:95152)
[2018-08-02 14:45:44 -0400] [95143] [CRITICAL] WORKER TIMEOUT (pid:95153)
[2018-08-02 14:45:44 -0400] [95143] [CRITICAL] WORKER TIMEOUT (pid:95154)
[2018-08-02 14:45:44 -0400] [95143] [CRITICAL] WORKER TIMEOUT (pid:95155)
[2018-08-02 16:04:28 -0400] [96376] [CRITICAL] WORKER TIMEOUT (pid:96384)
[2018-08-02 16:04:29 -0400] [96376] [CRITICAL] WORKER TIMEOUT (pid:96385)
[2018-08-02 16:04:29 -0400] [96376] [CRITICAL] WORKER TIMEOUT (pid:96386)
[2018-08-02 16:04:29 -0400] [96376] [CRITICAL] WORKER TIMEOUT (pid:96387)
[2018-08-02 16:04:29 -0400] [96376] [CRITICAL] WORKER TIMEOUT (pid:96388)
[2018-08-02 16:04:29 -0400] [96376] [CRITICAL] WORKER TIMEOUT (pid:96380)
[2018-08-02 16:04:29 -0400] [96376] [CRITICAL] WORKER TIMEOUT (pid:96381)
[2018-08-02 16:04:29 -0400] [96376] [CRITICAL] WORKER TIMEOUT (pid:96382)
[2018-08-02 16:04:29 -0400] [96376] [CRITICAL] WORKER TIMEOUT (pid:96383)
[2018-08-02 16:23:41 -0400] [96376] [CRITICAL] WORKER TIMEOUT (pid:97472)
[2018-08-02 16:23:41 -0400] [96376] [CRITICAL] WORKER TIMEOUT (pid:97473)
[2018-08-02 16:23:41 -0400] [96376] [CRITICAL] WORKER TIMEOUT (pid:97474)
[2018-08-02 16:23:41 -0400] [96376] [CRITICAL] WORKER TIMEOUT (pid:97475)
[2018-08-02 16:23:41 -0400] [96376] [CRITICAL] WORKER TIMEOUT (pid:97476)
[2018-08-02 16:23:41 -0400] [96376] [CRITICAL] WORKER TIMEOUT (pid:97477)
[2018-08-02 16:23:41 -0400] [96376] [CRITICAL] WORKER TIMEOUT (pid:97468)
[2018-08-02 16:23:41 -0400] [96376] [CRITICAL] WORKER TIMEOUT (pid:97470)
[2018-08-02 16:23:41 -0400] [96376] [CRITICAL] WORKER TIMEOUT (pid:97471)
[2018-08-02 16:52:34 -0400] [96376] [CRITICAL] WORKER TIMEOUT (pid:97796)
[2018-08-02 17:19:02 -0400] [96376] [CRITICAL] WORKER TIMEOUT (pid:97798)
[2018-08-02 17:27:58 -0400] [96376] [CRITICAL] WORKER TIMEOUT (pid:98498)
[2018-08-02 17:27:58 -0400] [96376] [CRITICAL] WORKER TIMEOUT (pid:97800)
[2018-08-02 17:27:58 -0400] [96376] [CRITICAL] WORKER TIMEOUT (pid:97801)
[2018-08-02 17:27:58 -0400] [96376] [CRITICAL] WORKER TIMEOUT (pid:97802)
[2018-08-02 17:27:58 -0400] [96376] [CRITICAL] WORKER TIMEOUT (pid:97803)
[2018-08-02 17:27:58 -0400] [96376] [CRITICAL] WORKER TIMEOUT (pid:97805)
[2018-08-02 17:27:58 -0400] [96376] [CRITICAL] WORKER TIMEOUT (pid:97807)
[2018-08-02 17:27:58 -0400] [96376] [CRITICAL] WORKER TIMEOUT (pid:97808)
[2018-08-02 17:27:58 -0400] [96376] [CRITICAL] WORKER TIMEOUT (pid:98186)
[2018-08-02 19:34:15 -0400] [96376] [CRITICAL] WORKER TIMEOUT (pid:98563)
[2018-08-02 19:34:15 -0400] [96376] [CRITICAL] WORKER TIMEOUT (pid:98564)
[2018-08-02 19:34:15 -0400] [96376] [CRITICAL] WORKER TIMEOUT (pid:98565)
[2018-08-02 19:34:15 -0400] [96376] [CRITICAL] WORKER TIMEOUT (pid:98566)
[2018-08-02 19:34:15 -0400] [96376] [CRITICAL] WORKER TIMEOUT (pid:98567)
[2018-08-02 19:34:15 -0400] [96376] [CRITICAL] WORKER TIMEOUT (pid:98568)
[2018-08-02 19:34:15 -0400] [96376] [CRITICAL] WORKER TIMEOUT (pid:98569)
[2018-08-02 19:34:15 -0400] [96376] [CRITICAL] WORKER TIMEOUT (pid:98570)
[2018-08-02 19:34:15 -0400] [96376] [CRITICAL] WORKER TIMEOUT (pid:98571)
[2018-08-03 06:00:40 -0400] [96376] [CRITICAL] WORKER TIMEOUT (pid:99072)
[2018-08-03 06:00:40 -0400] [96376] [CRITICAL] WORKER TIMEOUT (pid:99073)
[2018-08-03 06:00:40 -0400] [96376] [CRITICAL] WORKER TIMEOUT (pid:99065)
[2018-08-03 06:00:40 -0400] [96376] [CRITICAL] WORKER TIMEOUT (pid:99066)
[2018-08-03 06:00:40 -0400] [96376] [CRITICAL] WORKER TIMEOUT (pid:99067)
[2018-08-03 06:00:40 -0400] [96376] [CRITICAL] WORKER TIMEOUT (pid:99068)
[2018-08-03 06:00:40 -0400] [96376] [CRITICAL] WORKER TIMEOUT (pid:99069)
[2018-08-03 06:00:40 -0400] [96376] [CRITICAL] WORKER TIMEOUT (pid:99070)
[2018-08-03 06:00:40 -0400] [96376] [CRITICAL] WORKER TIMEOUT (pid:99071)
[2018-08-03 07:48:29 -0400] [96376] [CRITICAL] WORKER TIMEOUT (pid:99174)
[2018-08-03 07:48:29 -0400] [96376] [CRITICAL] WORKER TIMEOUT (pid:99175)
[2018-08-03 07:48:29 -0400] [96376] [CRITICAL] WORKER TIMEOUT (pid:99176)
[2018-08-03 07:48:29 -0400] [96376] [CRITICAL] WORKER TIMEOUT (pid:99177)
[2018-08-03 07:48:29 -0400] [96376] [CRITICAL] WORKER TIMEOUT (pid:99178)
[2018-08-03 07:48:29 -0400] [96376] [CRITICAL] WORKER TIMEOUT (pid:99179)
[2018-08-03 07:48:29 -0400] [96376] [CRITICAL] WORKER TIMEOUT (pid:99180)
[2018-08-03 07:48:29 -0400] [96376] [CRITICAL] WORKER TIMEOUT (pid:99181)
[2018-08-03 07:48:29 -0400] [96376] [CRITICAL] WORKER TIMEOUT (pid:99182)
[2018-08-03 09:04:40 -0400] [417] [CRITICAL] WORKER TIMEOUT (pid:421)
[2018-08-03 09:04:40 -0400] [417] [CRITICAL] WORKER TIMEOUT (pid:423)
[2018-08-03 09:04:40 -0400] [417] [CRITICAL] WORKER TIMEOUT (pid:425)
[2018-08-03 09:04:40 -0400] [417] [CRITICAL] WORKER TIMEOUT (pid:428)
[2018-08-03 09:04:40 -0400] [417] [CRITICAL] WORKER TIMEOUT (pid:432)
[2018-08-10 09:18:34 +0000] [5422] [CRITICAL] WORKER TIMEOUT (pid:5427)
[2018-08-10 10:46:58 +0000] [5422] [CRITICAL] WORKER TIMEOUT (pid:5429)
